kind: ConfigMap
apiVersion: v1
metadata:
  name: project-map
data:
  projects.map: |
    num  3
    0  PROJECT_ID_1
    1  PROJECT_ID_2
    2  PROJECT_ID_3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1 # Update the replicas from 2 to 4
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: haproxy
          image: IMAGE_URL
          command: [ "/bin/sh", "-c" ]
          args:
              - /docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg -d
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /data/projects.map
              name: project-map
              subPath: projects.map
      volumes:
        - name: project-map
          configMap:
            name: project-map
            items:
              - key: projects.map
                path: projects.map
---
apiVersion: v1
kind: Service
metadata:
  name: vertex-ai-claude-load-balancer
spec:
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
